//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int Id { get; set; }
        public Nullable<int> kullanici { get; set; }
        public string e_posta { get; set; }
        public string mesaj { get; set; }
        public Nullable<bool> okundu_Bilgi { get; set; }
    
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
