//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hastane_ProjeEntities : DbContext
    {
        public Hastane_ProjeEntities()
            : base("name=Hastane_ProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adenopaty> Adenopaty { get; set; }
        public virtual DbSet<Focality> Focality { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<M> M { get; set; }
        public virtual DbSet<N> N { get; set; }
        public virtual DbSet<Pathology> Pathology { get; set; }
        public virtual DbSet<Physical_Examination> Physical_Examination { get; set; }
        public virtual DbSet<Response> Response { get; set; }
        public virtual DbSet<Risk> Risk { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T> T { get; set; }
        public virtual DbSet<Thyroid_Function> Thyroid_Function { get; set; }
        public virtual DbSet<Tiroid_Verileri> Tiroid_Verileri { get; set; }
    }
}
