//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiroid_Verileri
    {
        public int Id { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<bool> smoking { get; set; }
        public Nullable<bool> hx_Smoking { get; set; }
        public Nullable<bool> hx_Radiothreapy { get; set; }
        public Nullable<int> thyroid_Function { get; set; }
        public Nullable<int> physical_Examination { get; set; }
        public Nullable<int> adenopaty { get; set; }
        public Nullable<int> pathology { get; set; }
        public Nullable<int> focality { get; set; }
        public Nullable<int> risk { get; set; }
        public Nullable<int> t { get; set; }
        public Nullable<int> n { get; set; }
        public Nullable<int> m { get; set; }
        public Nullable<int> stage { get; set; }
        public Nullable<int> response { get; set; }
        public Nullable<int> recurred { get; set; }
        public Nullable<System.DateTime> olcum_Tarihi { get; set; }
        public Nullable<int> kullanici { get; set; }
    
        public virtual Adenopaty Adenopaty1 { get; set; }
        public virtual Focality Focality1 { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual M M1 { get; set; }
        public virtual N N1 { get; set; }
        public virtual Pathology Pathology1 { get; set; }
        public virtual Physical_Examination Physical_Examination1 { get; set; }
        public virtual Response Response1 { get; set; }
        public virtual Risk Risk1 { get; set; }
        public virtual Stage Stage1 { get; set; }
        public virtual T T1 { get; set; }
        public virtual Thyroid_Function Thyroid_Function1 { get; set; }
    }
}
